- name: '[Linux] configure nginx'
import_playbook: playbooks/configure_nginx_web_server.yml

- hosts: windows
  gather_facts: false
  roles:
    - chocolatey

- name: '[Windows] configure IIS'
  import_playbook: playbooks/config_iis_web_server.yml
